#!/system/bin/sh
/system/xbin/echo 2048 > /proc/sys/kernel/msgmni
/system/xbin/echo 64000 > /proc/sys/kernel/msgmax
/system/xbin/echo 268435456 > /proc/sys/kernel/shmmax
/system/xbin/echo 500 512000 64 2048 > /proc/sys/kernel/sem
/system/xbin/sysctl -w net.core.wmem_max=524288
/system/xbin/sysctl -w net.core.rmem_max=524288
/system/xbin/sysctl -w net.ipv4.tcp_tw_recycle=1
/system/xbin/sysctl -w net.ipv4.tcp_rmem='6144 87380 524288'
/system/xbin/sysctl -w net.ipv4.tcp_wmem='6144 87380 524288'

